### ISSUE TITLE
Not Isomorphic

### ISSUE THREAD

**Issue by JoeGrasso** [AndrewKovalenko/swipe-toggle-switch#1]
HammerJS calls the window element on mounting and if your app is isomorphic this component won't work.

**Comment by AndrewKovalenko** [comment]
@JoeGrasso first, I never told this component is isomorphic and never had intention to make it so.
second, if the problem is in _HammerJs_ why do you write here?
third, if you want to use it isomorphic - fork repo, make your changes and create a PR instead expecting me to make component satisfy **your** needs. I'll be more than happy to make you a contributor.
